/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Royalties2981TestImpl,
  Royalties2981TestImplInterface,
} from "../Royalties2981TestImpl";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "amount",
        type: "uint96",
      },
    ],
    name: "calculateRoyaltiesTest",
    outputs: [
      {
        components: [
          {
            internalType: "address payable",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "value",
            type: "uint96",
          },
        ],
        internalType: "struct LibPart.Part[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_salePrice",
        type: "uint256",
      },
    ],
    name: "royaltyInfo",
    outputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "royaltyAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102f2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063028a11bd1461003b5780632a55205a14610064575b600080fd5b61004e6100493660046101d3565b610085565b60405161005b919061025b565b60405180910390f35b610077610072366004610221565b6100a3565b60405161005b929190610242565b606061009a83836001600160601b03166100b2565b90505b92915050565b60609190911c91600a90910490565b606080826100c157905061009d565b6000620f4240606485020460640290506127108110610127576040805162461bcd60e51b815260206004820152601960248201527f526f79616c7469657320323938312c207468616e203130302500000000000000604482015290519081900360640190fd5b60408051600180825281830190925290816020015b6101446101bc565b81526020019060019003908161013c579050509150848260008151811061016757fe5b6020026020010151600001906001600160a01b031690816001600160a01b031681525050808260008151811061019957fe5b6020908102919091018101516001600160601b0390921691015250905092915050565b604080518082019091526000808252602082015290565b600080604083850312156101e5578182fd5b82356001600160a01b03811681146101fb578283fd5b915060208301356001600160601b0381168114610216578182fd5b809150509250929050565b60008060408385031215610233578182fd5b50508035926020909101359150565b6001600160a01b03929092168252602082015260400190565b602080825282518282018190526000919060409081850190868401855b828110156102af57815180516001600160a01b031685528601516001600160601b0316868501529284019290850190600101610278565b509197965050505050505056fea2646970667358221220ad9d2b450f6781af8e7bad1e4bf8b71286fb0cef0d92efeb05e90457d44119fd64736f6c63430007060033";

export class Royalties2981TestImpl__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Royalties2981TestImpl> {
    return super.deploy(overrides || {}) as Promise<Royalties2981TestImpl>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Royalties2981TestImpl {
    return super.attach(address) as Royalties2981TestImpl;
  }
  connect(signer: Signer): Royalties2981TestImpl__factory {
    return super.connect(signer) as Royalties2981TestImpl__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Royalties2981TestImplInterface {
    return new utils.Interface(_abi) as Royalties2981TestImplInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Royalties2981TestImpl {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as Royalties2981TestImpl;
  }
}
