/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ERC1271Interface extends ethers.utils.Interface {
  functions: {
    "ERC1271_INTERFACE_ID()": FunctionFragment;
    "ERC1271_RETURN_INVALID_SIGNATURE()": FunctionFragment;
    "ERC1271_RETURN_VALID_SIGNATURE()": FunctionFragment;
    "isValidSignature(bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ERC1271_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1271_RETURN_INVALID_SIGNATURE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC1271_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1271_RETURN_INVALID_SIGNATURE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export class ERC1271 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ERC1271Interface;

  functions: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  ERC1271_RETURN_INVALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

  ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

  isValidSignature(
    _hash: BytesLike,
    _signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<string>;

    ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC1271_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
